# Generated by Django 5.2.11 on 2026-02-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="Term or semester, e.g. Term 1", max_length=50
                    ),
                ),
                ("marks_obtained", models.FloatField()),
                ("max_marks", models.FloatField(default=100.0)),
                (
                    "grade_letter",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("percentage", models.FloatField(default=0.0)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("midterm", "Midterm"),
                            ("final", "Final"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grades",
                        to="academics.classroom",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "grades",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["student", "subject"], name="grades_student_f99f41_idx"
                    ),
                    models.Index(
                        fields=["school", "term"], name="grades_school__7b71df_idx"
                    ),
                ],
            },
        ),
    ]
