# Generated by Django 5.2.11 on 2026-02-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                (
                    "applicant_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "applicant_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("applying_for_class", models.CharField(max_length=50)),
                ("academic_year", models.CharField(max_length=20)),
                (
                    "parent_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "parent_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "previous_school",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("applied_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "admissions",
                "ordering": ["-applied_date"],
            },
        ),
    ]
