# Generated by Django 5.2.11 on 2026-02-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="e.g. '10'", max_length=50)),
                (
                    "section",
                    models.CharField(
                        blank=True, default="", help_text="e.g. 'A'", max_length=10
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=40)),
                (
                    "academic_year",
                    models.CharField(help_text="e.g. '2024-2025'", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homeroom_classes",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "classrooms",
                "ordering": ["name", "section"],
                "indexes": [
                    models.Index(
                        fields=["school", "status"],
                        name="classrooms_school__1581f6_idx",
                    ),
                    models.Index(
                        fields=["academic_year"], name="classrooms_academi_31c0d0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "code",
                    models.CharField(help_text="Unique per school", max_length=50),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("elective", "Elective"),
                            ("extracurricular", "Extracurricular"),
                        ],
                        default="core",
                        max_length=20,
                    ),
                ),
                ("credits", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["school", "status"], name="subjects_school__16eb8d_idx"
                    )
                ],
                "unique_together": {("school", "code")},
            },
        ),
    ]
